[package]
name = "bystro-vcf"
version = "0.1.0"
authors = ["Alex Kotlar <akotlar@bu.edu>"]
edition = "2018"

[dependencies]
log = "0.4.6"
crossbeam = "0.7.2"
num_cpus = "1.10.0"
hashbrown = "0.3.0"
atoi = "0.3.1"
itoa = "0.4.3"
memchr = "2.2.0"
ryu = "1.0.0"
