beanstalkd:
  addresses:
    - <host1>:<port1>
  tubes:
    annotation:
      submission: annotation
      events: annotation_events
    saveFromQuery:
      submission: saveFromQuery
      events: saveFromQuery_events
    index:
      submission: index
      events: index_events
    filters:
      submission: filters
      events: filters_events
    ancestry:
      submission: ancestry
      events: ancestry_events
    proteomics:
      submission: proteomics
      events: proteomics_events
    prs:
      submission: prs
      events: prs_events