---
assembly: ce11
chromosomes:
- chrI
- chrII
- chrIII
- chrIV
- chrM
- chrV
- chrX
database_dir: '~'
files: '~'
files_dir: ~
statistics:
  dbSNPnameField: ~
  exonicAlleleFunctionField: refSeq.exonicAlleleFunction
  outputExtensions:
    json: .statistics.json
    qc: .statistics.qc.tab
    tab: .statistics.tab
  refTrackField: ref
  siteTypeField: refSeq.siteType
  programPath: bystro-stats
temp_dir: '~'
snpProcessor: bystro-snp
vcfProcessor: bystro-vcf
tracks:
- name: ref
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/ce11/chromosomes/
  remote_files:
  - chrI.fa.gz
  - chrII.fa.gz
  - chrIII.fa.gz
  - chrIV.fa.gz
  - chrM.fa.gz
  - chrV.fa.gz
  - chrX.fa.gz
  type: reference
- features:
  - name
  - name2
  name: refSeq
  nearest:
  - name
  - name2
  sql_statement: SELECT * FROM ce11.refGene
  type: gene
- name: phastCons
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/ce11/phastCons26way/
  remote_files:
  - ce11.phastCons26way.wigFix.gz
  type: score
- name: phyloP
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/ce11/phyloP26way/
  remote_files:
  - ce11.phyloP26way.wigFix.gz
  type: score

