---
assembly: hg19
chromosomes:
- chr1
- chr2
- chr3
- chr4
- chr5
- chr6
- chr7
- chr8
- chr9
- chr10
- chr11
- chr12
- chr13
- chr14
- chr15
- chr16
- chr17
- chr18
- chr19
- chr20
- chr21
- chr22
- chrM
- chrX
- chrY
database_dir: ~
files_dir: ~
statistics:
  refTrackField: ref
  dbSNPnameField: dbSNP.name
  exonicAlleleFunctionField: refSeq.exonicAlleleFunction
  outputExtensions:
    json: .statistics.json
    qc: .statistics.qc.tab
    tab: .statistics.tab
  siteTypeField: refSeq.siteType
  programPath: bystro-stats
temp_dir: ~
snpProcessor: bystro-snp
vcfProcessor: bystro-vcf
tracks:
- local_files:
  - chr*.fa.gz
  name: ref
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/chromosomes/
  remote_files:
  - chr1.fa.gz
  - chr2.fa.gz
  - chr3.fa.gz
  - chr4.fa.gz
  - chr5.fa.gz
  - chr6.fa.gz
  - chr7.fa.gz
  - chr8.fa.gz
  - chr9.fa.gz
  - chr10.fa.gz
  - chr11.fa.gz
  - chr12.fa.gz
  - chr13.fa.gz
  - chr14.fa.gz
  - chr15.fa.gz
  - chr16.fa.gz
  - chr17.fa.gz
  - chr18.fa.gz
  - chr19.fa.gz
  - chr20.fa.gz
  - chr21.fa.gz
  - chr22.fa.gz
  - chrM.fa.gz
  - chrX.fa.gz
  - chrY.fa.gz
  type: reference
- features:
  - kgID
  - mRNA
  - spID
  - spDisplayID
  - protAcc
  - description
  - rfamAcc
  - name
  - name2
  join:
    features:
    - alleleID
    - phenotypeList
    - clinicalSignificance
    - type
    - origin
    - numberSubmitters
    - reviewStatus
    - chromStart
    - chromEnd
    track: clinvar
  name: refSeq
  nearest:
  - name
  - name2
  sql_statement: SELECT * FROM hg19.refGene LEFT JOIN hg19.kgXref ON hg19.kgXref.refseq
    = hg19.refGene.name
  type: gene
- name: phastCons
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phastCons100way/hg19.100way.phastCons/
  remote_files:
  - chr1.phastCons100way.wigFix.gz
  - chr2.phastCons100way.wigFix.gz
  - chr3.phastCons100way.wigFix.gz
  - chr4.phastCons100way.wigFix.gz
  - chr5.phastCons100way.wigFix.gz
  - chr6.phastCons100way.wigFix.gz
  - chr7.phastCons100way.wigFix.gz
  - chr8.phastCons100way.wigFix.gz
  - chr9.phastCons100way.wigFix.gz
  - chr10.phastCons100way.wigFix.gz
  - chr11.phastCons100way.wigFix.gz
  - chr12.phastCons100way.wigFix.gz
  - chr13.phastCons100way.wigFix.gz
  - chr14.phastCons100way.wigFix.gz
  - chr15.phastCons100way.wigFix.gz
  - chr16.phastCons100way.wigFix.gz
  - chr17.phastCons100way.wigFix.gz
  - chr18.phastCons100way.wigFix.gz
  - chr19.phastCons100way.wigFix.gz
  - chr20.phastCons100way.wigFix.gz
  - chr21.phastCons100way.wigFix.gz
  - chr22.phastCons100way.wigFix.gz
  - chrX.phastCons100way.wigFix.gz
  - chrY.phastCons100way.wigFix.gz
  - chrM.phastCons100way.wigFix.gz
  type: score
- name: phyloP
  remote_dir: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/phyloP100way/hg19.100way.phyloP100way/
  remote_files:
  - chr1.phyloP100way.wigFix.gz
  - chr2.phyloP100way.wigFix.gz
  - chr3.phyloP100way.wigFix.gz
  - chr4.phyloP100way.wigFix.gz
  - chr5.phyloP100way.wigFix.gz
  - chr6.phyloP100way.wigFix.gz
  - chr7.phyloP100way.wigFix.gz
  - chr8.phyloP100way.wigFix.gz
  - chr9.phyloP100way.wigFix.gz
  - chr10.phyloP100way.wigFix.gz
  - chr11.phyloP100way.wigFix.gz
  - chr12.phyloP100way.wigFix.gz
  - chr13.phyloP100way.wigFix.gz
  - chr14.phyloP100way.wigFix.gz
  - chr15.phyloP100way.wigFix.gz
  - chr16.phyloP100way.wigFix.gz
  - chr17.phyloP100way.wigFix.gz
  - chr18.phyloP100way.wigFix.gz
  - chr19.phyloP100way.wigFix.gz
  - chr20.phyloP100way.wigFix.gz
  - chr21.phyloP100way.wigFix.gz
  - chr22.phyloP100way.wigFix.gz
  - chrX.phyloP100way.wigFix.gz
  - chrY.phyloP100way.wigFix.gz
  - chrM.phyloP100way.wigFix.gz
  type: score
- local_files:
  # Note that chrM for hg19 is not equal to GRCh37.p13 MT
  - whole_genome_SNVs.tsv.chr*.bed.gz
  name: cadd
  sorted_guaranteed: 1
  type: cadd
- build_field_transformations:
    alleleFreqs: split [,]
    alleleNs: split [,]
    alleles: split [,]
    func: split [,]
    observed: split [\/]
  features:
  - name
  - strand
  - observed
  - class
  - func
  - alleles
  - alleleNs: number
  - alleleFreqs: number
  name: dbSNP
  sql_statement: SELECT * FROM hg19.snp146
  type: sparse
- based: 1
  build_field_transformations:
    chrom: chr .
    clinicalSignificance: split [;]
    origin: split [;]
    phenotypeList: split [;]
    reviewStatus: split [;]
    type: split [;]
    reviewStatus: split[;]
  build_row_filters:
    Assembly: == GRCh37
  features:
  - alleleID: number
  - phenotypeList
  - clinicalSignificance
  - type
  - origin
  - numberSubmitters: number
  - reviewStatus
  - referenceAllele
  - alternateAllele
  fieldMap:
    '#AlleleID': alleleID
    AlternateAllele: alternateAllele
    Chromosome: chrom
    ClinicalSignificance: clinicalSignificance
    Origin: origin
    OtherIDs: otherIDs
    PhenotypeIDS: phenotypeIDs
    NumberSubmitters: numberSubmitters
    PhenotypeList: phenotypeList
    ReferenceAllele: referenceAllele
    ReviewStatus: reviewStatus
    Start: chromStart
    Stop: chromEnd
    Type: type
  name: clinvar
  remote_files:
  - ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz
  type: sparse

