---
assembly: rn6
chromosomes:
- chr1
- chr2
- chr3
- chr4
- chr5
- chr6
- chr7
- chr8
- chr9
- chr10
- chr11
- chr12
- chr13
- chr14
- chr15
- chr16
- chr17
- chr18
- chr19
- chr20
- chrM
- chrX
database_dir: '~'
files: '~'
files_dir: ~
statistics:
  dbSNPnameField: ~
  exonicAlleleFunctionField: refSeq.exonicAlleleFunction
  outputExtensions:
    json: .statistics.json
    qc: .statistics.qc.tab
    tab: .statistics.tab
  refTrackField: ref
  siteTypeField: refSeq.siteType
  programPath: bystro-stats
temp_dir: '~'
fileProcessors:
  snp:
    args: --emptyField ! --minGq .95
    program: bystro-snp
  vcf:
    args: --emptyField ! --keepId --keepPos
    program: bystro-vcf
tracks:
- name: ref
  remote_dir: http://hgdownload.cse.ucsc.edu/goldenPath/rn6/bigZips/
  remote_files:
  - rn6.fa.gz
  type: reference
- features:
  - name
  - name2
  name: refSeq
  nearest:
  - name
  - name2
  sql_statement: SELECT * FROM rn6.refGene
  type: gene
- local_files:
  - rn6.phastCons20way.wigFix.gz
  name: phastCons
  remote_dir: http://hgdownload.cse.ucsc.edu/goldenPath/rn6/phastCons20way/
  remote_files:
  - rn6.phastCons20way.wigFix.gz
  type: score
- local_files:
  - rn6.phyloP20way.wigFix.gz
  name: phyloP
  remote_dir: http://hgdownload.cse.ucsc.edu/goldenPath/rn6/phyloP20way/
  remote_files:
  - rn6.phyloP20way.wigFix.gz
  type: score
