name: conda-build

on:
  pull_request:
    paths:
      - "perl/**"
      - "python/**"
      - "go/**"
      - "config/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: true
          python-version: ${{ matrix.python-version }}
      - name: Install Bystro using Maturin
        run: |
          . .initialize_conda_env.sh
          make install
          echo "PATH=$CONDA/bin:$PATH" >> $GITHUB_ENV
        shell: bash
      - name: Verify Bystro wheel exists
        run: |
          WHEEL_FILE=$(find python/target/wheels -name 'bystro-*-cp311-cp311-manylinux*x86_64.whl' | head -n 1)
          if [[ -z "$WHEEL_FILE" ]]; then
            echo "Expected Bystro manylinux x86_64 wheel not found!"
            exit 1
          fi
          echo "Bystro wheel found! Build succeeded."
      - name: Verify bystro-api is installed
        run: |
          set -e
          bystro-api --help
          echo "bystro-api installed successfully"
